local test = require("test")
local data_error = require("data_error")

local function define_tests()
    test.describe("cotique.bitbucket_provider.client:data_error mapping", function()
        test.it("builds a DataError with the confirmed writable.write envelope shape", function()
            local err = data_error.new("some_code", "some message", true, "item")
            test.eq(err.code, "some_code")
            test.eq(err.message, "some message")
            test.eq(err.retriable, true)
            test.eq(err.scope, "item")
        end)

        test.it("defaults retriable to false and scope to provider", function()
            local err = data_error.new("some_code", "some message")
            test.eq(err.retriable, false)
            test.eq(err.scope, "provider")
        end)

        test.it("maps 401 to a non-retriable connection-scoped auth failure", function()
            local err = data_error.from_http(401, nil, "Unauthorized")
            test.eq(err.code, "auth_failed")
            test.eq(err.retriable, false)
            test.eq(err.scope, "connection")
        end)

        test.it("maps 404 to a non-retriable item-scoped not_found", function()
            local err = data_error.from_http(404, nil, "Not Found")
            test.eq(err.code, "not_found")
            test.eq(err.scope, "item")
        end)

        test.it("maps 429 to a retriable provider-scoped rate_limited", function()
            local err = data_error.from_http(429, nil, "Rate limit exceeded")
            test.eq(err.code, "rate_limited")
            test.eq(err.retriable, true)
            test.eq(err.scope, "provider")
        end)

        test.it("maps 5xx to a retriable provider_unavailable", function()
            local err = data_error.from_http(503, nil, "Service Unavailable")
            test.eq(err.code, "provider_unavailable")
            test.eq(err.retriable, true)
            test.eq(err.scope, "provider")
        end)

        test.it("maps other 4xx to a non-retriable invalid_request", function()
            local err = data_error.from_http(400, nil, "Bad Request")
            test.eq(err.code, "invalid_request")
            test.eq(err.retriable, false)
            test.eq(err.scope, "flow")
        end)

        test.it("prefers the decoded Bitbucket error.message body when present", function()
            local err = data_error.from_http(400, { error = { message = "workspace not found" } }, "{}")
            test.eq(err.message, "workspace not found")
        end)

        test.it("maps a transport failure to a retriable provider-scoped network_error", function()
            local err = data_error.from_transport("connection refused")
            test.eq(err.code, "network_error")
            test.eq(err.retriable, true)
            test.eq(err.scope, "provider")
        end)
    end)
end

local run_cases = test.run_cases(define_tests)
return { run = function(options) return run_cases(options) end }
